Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'Gemfile'